[package]
name = "andrea/main"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

# Datastore
suphisdatastoremodule = "skylord-103/suphisdatastoremodule@1.0.0"

# Network
BridgeNet2 = "ffrostflame/bridgenet2@^0.5"

# Utility
janitor = "howmanysmall/janitor@1.15.6"
trove = "sleitnick/trove@1.0.1"
signal = "sleitnick/signal@1.5.0"

# UI
fusion = "elttob/fusion@0.3.0"
ui-labs = "pepeeltoro41/ui-labs@2.4.0"
uiparticle = "kumarion/uiparticle@0.0.1"

conch = "alicesaidhi/conch@0.3.0"
conch-ui = "alicesaidhi/conch-ui@0.3.0"

# Visuals
windshake = "boatbomber/windshake@2.0.3"
# windlines = "aspecky/windlines@1.0.0" -- I have my own version